baseURL = "/"
languageCode = "es-es"
title = "Contratos y Decretos"
taxonomies = []
publishDir = "docs"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_cache$", "\\.knit\\.md$", "\\.utf8\\.md$", "_files$"]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true